---
title: "overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(paintbynumbr)
library(dplyr)
library(ggplot2) # not required for main functions
library(magrittr)
library(tidyr)
library(ggplot2)
library(colorspace)
library(paintbynumbr)
library(stringr)




# Filtering down to Texas to speed up plotting times a bit...
data("fars_accidents") # note: still including unknowns/unreported

fars_tx <- fars_accidents %>%
  #filter(LONGITUD > -200, LATITUDE > 25 & LATITUDE < 50) %>% # continental US
  filter(STATENAME == "Texas") %>%
  filter(LONGITUD < 0 & LATITUDE < 100) %>% # removing `unknown` records
  mutate(color_id = paint_by_2d_scale_hsv(paint_by_1 = LONGITUD, paint_by_2 = LATITUDE))

# Continuous "Legend" Gradient showing all possible values <- might be worth allowing manually setting max/min (
  # e.g. to allow 0-10 when lowest observed value happens to be 1)

# Note: different dimensions than input, so can't pipe directly
fars_tx_key <- paint_by_2d_scale_hsv_legend(paint_by_1 = fars_tx$LONGITUD,
                                                     paint_by_2 = fars_tx$LATITUDE,
                                                     resolution = 30) %>%
  ggplot() +
  aes(x = labels_x,
      y = labels_y,
      fill = color_id) +
  geom_tile() +
  scale_fill_identity() +
  labs(x = "Longitude",
       y = "Latitude",
       title = "Texas FARS Data: Color Gradient by Coordinates")

fars_tx_key

# Plotting simple 'map' with point coordinates:
  # could use e.g. `st_as_sf()` for GIS plotting
fars_tx %>%
  ggplot() + 
  aes(
    x = LONGITUD,
    y = LATITUDE,
    color = color_id
  ) +
  geom_point() +
  scale_color_identity() + # key step
  theme_minimal()

# filtering to cases with reported weather

fars_tx_weather <- fars_tx %>%
    dplyr::filter(dplyr::across(.cols = c(WEATHERNAME, LGT_CONDNAME),
                                .fns = ~!str_detect(., "((?i)not reported)|(?i)unknown|(?i)not available")))

# Plotting against weather and light conditions:
fars_tx_weather %>%
  ggplot() + 
  aes(
    y = WEATHERNAME,
    x = LGT_CONDNAME,
    color = color_id
  ) +
  geom_jitter() +
  scale_color_identity() + # key step
  theme_minimal()

# Categorical coloring by Weather and Lighting Conditions
  # color_family_gen also accepts numeric values for one or both parameters 
  # Demonstrating manual setting of stop/start angles; realistically probably 
    # have to manually order 'meaningful' values to get intuitive colors

fars_tx_weather %>%
    mutate(weather_color_id = color_family_gen(level_1 = WEATHERNAME, level_2 = LGT_CONDNAME,
                                               start_angle = 120, stop_angle = 360)) %>%
  ggplot() + 
  aes(
    x = WEATHERNAME,
    y = LGT_CONDNAME,
    fill = weather_color_id
  ) +
  geom_tile() +
  scale_fill_identity() + # key step
  theme_minimal()

# Legend for complete cases:

  
fars_tx_key_weather <- color_family_gen_legend(level_1 = fars_tx_weather$WEATHERNAME,
                                               level_2 = fars_tx_weather$LGT_CONDNAME,
                                               resolution = 30, start_angle = 90, stop_angle = 360) %>%
  ggplot() +
  aes(x = labels_x,
      y = labels_y,
      fill = color_id) + # note this is a default name assigned in-function
  geom_tile() +
  scale_fill_identity() +
  labs(x = "Weather Conditions",
       y = "Light Conditions",
       title = "Texas FARS Data: Color Gradient by Weather/Light Conditions")

fars_tx_key

# Plotting with map again (excluding unknown/unreported weather)

fars_tx_weather %>%
   mutate(weather_color_id = color_family_gen(level_1 = WEATHERNAME, level_2 = LGT_CONDNAME,
                                               start_angle = 90, stop_angle = 360)) %>%
  ggplot() + 
  aes(
    x = LONGITUD,
    y = LATITUDE,
    color = weather_color_id
  ) +
  geom_point() +
  scale_color_identity() + # key step
  theme_minimal()



```
